prometheus:
  prometheusSpec:
    retention: 1h
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

grafana:
  persistence:
    enabled: false
  service:
    type: NodePort
