apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter-monitor
  namespace: default
  labels:
    app: nginx-health
    prometheus: kube-prometheus  # 新增这一行，至关重要
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: 9113
      path: /metrics
      interval: 15s
